# Generated by Django 2.2.2 on 2019-06-16 23:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.TextField()),
                ('dia_creada', models.DateTimeField(default=django.utils.timezone.now)),
                ('dia_publicada', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
